CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    type VARCHAR(255),
    message VARCHAR(500),
    read_status BOOLEAN,
    created_at TIMESTAMP
);
