CREATE TABLE penalties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT,
    user_id BIGINT,
    amount DOUBLE,
    reason VARCHAR(500),
    status VARCHAR(255),
    created_at TIMESTAMP
);
