spring.application.name=eureka

# Eureka discovery server port.
server.port=8761

# The server itself does not need to register/fetch registry.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
