CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT,
    user_id BIGINT,
    reservation_date DATE,
    expiry_date DATE,
    status VARCHAR(255)
);
