CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR(255),
    generated_by BIGINT,
    parameters VARCHAR(500),
    result VARCHAR(2000),
    created_at TIMESTAMP
);
