@baseUrl = http://localhost:8080
@token = pon_tu_token_aqui
@itemId = 1

### =========================
### MS-CATEGORY ENDPOINTS
### =========================

### 0. Login rapido para obtener token
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "suer",
  "password": "1234"
}

###
@token = {{login.response.body.token}}

### 1. Obtener todos
GET {{baseUrl}}/api/v1/categories
Authorization: Bearer {{token}}

### 2. Obtener por ID
GET {{baseUrl}}/api/v1/categories/{{itemId}}
Authorization: Bearer {{token}}

### 3. Crear nuevo
POST {{baseUrl}}/api/v1/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

### 4. Actualizar
PUT {{baseUrl}}/api/v1/categories/{{itemId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

### 5. Eliminar
DELETE {{baseUrl}}/api/v1/categories/{{itemId}}
Authorization: Bearer {{token}}
