spring.application.name=ms-loan

# Product service internal port.
server.port=8083

# Register product in Eureka for gateway discovery.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
# Faster heartbeat in dev to reduce startup waiting windows.
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15